[package]
name = "danya02_miner_rust"
version = "0.1.0"
authors = ["Danya Generalov <danya@danya02.ru>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
rust-crypto = "^0.2"
hex = "0.3.2"
